In [62]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [63]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix,classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier


import seaborn as sns
import matplotlib.pyplot as plt

In [64]:
df=pd.read_csv('/content/drive/MyDrive/Dataset/raw_diabates_data_v2.csv')

In [65]:
df.head(5)

,Gender,Age,Physical Activity,Smoking Status,Alcohol Intake,Glucose,Blood Pressure,Skin Thickness,Insulin,BMI,Cholesterol,Diabetes Pedigree Function,Family History,Hypertension,Outcome
0,Male,63.0,Moderate,Former,No,103.0,40.0,7.0,41.0,28.196216,167,1.393,Yes,Yes,Diabetic
1,Female,51.0,Moderate,Never,Regular,104.0,59.0,21.0,51.0,30.438114,209,0.815,No,No,Diabetic
2,Female,NaN,Moderate,Current,No,128.0,70.0,18.0,199.0,38.700428,170,0.244,No,No,Diabetic
3,Male,78.0,Low,Never,Occasional,148.0,72.0,15.0,110.0,44.861600,170,0.336,No,No,Diabetic
4,Male,32.0,High,Never,No,102.0,55.0,18.0,49.0,21.591572,211,1.146,Yes,No,Non-diabetic

In [66]:
df.shape

(20000, 15)

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Gender                      20000 non-null  object
 1   Age                         19998 non-null  float64
 2   Physical Activity           20000 non-null  object
 3   Smoking Status              19999 non-null  object
 4   Alcohol Intake              19999 non-null  object
 5   Glucose                     19995 non-null  float64
 6   Blood Pressure              19999 non-null  float64
 7   Skin Thickness              19999 non-null  float64
 8   Insulin                     19999 non-null  float64
 9   BMI                         19996 non-null  float64
 10  Cholesterol                 20000 non-null  int64
 11  Diabetes Pedigree Function  20000 non-null  float64
 12  Family History              20000 non-null  object
 13  Hypertension                20000 non-null  object
 14  Outcome                     20000 non-null  object
dtypes: float64(7), int64(1), object(7)
memory usage: 2.3+ MB

In [68]:
df.isnull().sum()

Gender                        0
Age                           2
Physical Activity             0
Smoking Status                1
Alcohol Intake                1
Glucose                       5
Blood Pressure                1
Skin Thickness                1
Insulin                       1
BMI                           4
Cholesterol                   0
Diabetes Pedigree Function    0
Family History                0
Hypertension                  0
Outcome                       0
dtype: int64

In [69]:
df.columns

Index(['Gender', 'Age', 'Physical Activity', 'Smoking Status',
       'Alcohol Intake', 'Glucose', 'Blood Pressure', 'Skin Thickness',
       'Insulin', 'BMI', 'Cholesterol', 'Diabetes Pedigree Function',
       'Family History', 'Hypertension', 'Outcome'],
      dtype='object')

In [70]:
df.describe()

,Age,Glucose,Blood Pressure,Skin Thickness,Insulin,BMI,Cholesterol,Diabetes Pedigree Function
count,19998.000000,19995.000000,19999.000000,19999.000000,19999.000000,19996.000000,20000.000000,20000.000000
mean,49.650465,119.667467,69.431872,20.105855,83.951198,32.008900,189.555400,1.310665
std,18.868875,30.141588,12.015618,9.131018,53.027822,6.913937,35.081701,0.693984
min,20.000000,40.000000,30.000000,7.000000,15.000000,15.000000,100.000000,0.100000
25%,35.000000,99.000000,61.000000,13.000000,40.000000,27.314143,166.000000,0.704750
50%,50.000000,120.000000,69.000000,20.000000,79.000000,31.994040,190.000000,1.316000
75%,64.000000,140.000000,78.000000,26.000000,120.000000,36.751218,213.000000,1.914000
max,888.000000,779.000000,114.000000,57.000000,276.000000,50.000000,320.000000,2.500000

In [71]:
numeric_cols = df.select_dtypes(include=["float64", "int64"]).columns
cat_cols     = df.select_dtypes(include=["object"]).columns

In [72]:
numeric_cols

Index(['Age', 'Glucose', 'Blood Pressure', 'Skin Thickness', 'Insulin', 'BMI',
       'Cholesterol', 'Diabetes Pedigree Function'],
      dtype='object')

In [73]:
cat_cols

Index(['Gender', 'Physical Activity', 'Smoking Status', 'Alcohol Intake',
       'Family History', 'Hypertension', 'Outcome'],
      dtype='object')

In [74]:
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [75]:
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [76]:
df.isnull().sum()

Gender                        0
Age                           0
Physical Activity             0
Smoking Status                0
Alcohol Intake                0
Glucose                       0
Blood Pressure                0
Skin Thickness                0
Insulin                       0
BMI                           0
Cholesterol                   0
Diabetes Pedigree Function    0
Family History                0
Hypertension                  0
Outcome                       0
dtype: int64

creat_list for categorical column

In [77]:
cat_cols_list = df.select_dtypes(include=["object"]).columns.tolist()

In [78]:
cat_cols_list

['Gender',
 'Physical Activity',
 'Smoking Status',
 'Alcohol Intake',
 'Family History',
 'Hypertension',
 'Outcome']

In [79]:
from sklearn.preprocessing import LabelEncoder

In [80]:
le = LabelEncoder()

In [81]:
for col in cat_cols_list:
    df[col] = le.fit_transform(df[col])

In [82]:
df.head()

,Gender,Age,Physical Activity,Smoking Status,Alcohol Intake,Glucose,Blood Pressure,Skin Thickness,Insulin,BMI,Cholesterol,Diabetes Pedigree Function,Family History,Hypertension,Outcome
0,1,63.0,2,1,0,103.0,40.0,7.0,41.0,28.196216,167,1.393,1,1,0
1,0,51.0,2,2,2,104.0,59.0,21.0,51.0,30.438114,209,0.815,0,0,0
2,0,50.0,2,0,0,128.0,70.0,18.0,199.0,38.700428,170,0.244,0,0,0
3,1,78.0,1,2,1,148.0,72.0,15.0,110.0,44.861600,170,0.336,0,0,0
4,1,32.0,0,2,0,102.0,55.0,18.0,49.0,21.591572,211,1.146,1,0,1

In [83]:
X = df.drop(columns=["Outcome"])
y = df["Outcome"]

In [84]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [85]:
sc= StandardScaler()

In [86]:

X_train = sc.fit_transform(X_train)
X_test  = sc.transform(X_test)

In [87]:
lr=LogisticRegression(max_iter=1000, random_state=42)

In [88]:
lr.fit(X_train,y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [89]:
y_pred=lr.predict(X_test)

In [90]:
lr.score(X_train,y_train)*100

98.0375

In [91]:
lr.score(X_test,y_test)*100

97.35000000000001

In [119]:
print("Accuracy  :", accuracy_score(y_test, y_pred))
print("Precision :", precision_score(y_test, y_pred))
print("Recall    :", recall_score(y_test, y_pred))
print("F1-Score  :", f1_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy  : 0.972
Precision : 0.9418238993710691
Recall    : 0.8887240356083086
F1-Score  : 0.9145038167938931

Confusion Matrix:
[[3289   37]
 [  75  599]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      3326
           1       0.94      0.89      0.91       674

    accuracy                           0.97      4000
   macro avg       0.96      0.94      0.95      4000
weighted avg       0.97      0.97      0.97      4000

In [92]:
re=RandomForestClassifier(n_estimators=100, random_state=42)

In [93]:
re.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [122]:
y2_pred=re.predict(X_test)

In [123]:
re.score(X_train,y_train)*100

100.0

In [124]:
re.score(X_test,y_test)*100

96.925

In [125]:
print("Accuracy  :", accuracy_score(y_test, y2_pred))
print("Precision :", precision_score(y_test, y2_pred))
print("Recall    :", recall_score(y_test, y2_pred))
print("F1-Score  :", f1_score(y_test, y2_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y2_pred))

print("\nClassification Report:")
print(classification_report(y_test, y2_pred))

Accuracy  : 0.96925
Precision : 0.9284603421461898
Recall    : 0.8857566765578635
F1-Score  : 0.9066059225512528

Confusion Matrix:
[[3280   46]
 [  77  597]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      3326
           1       0.93      0.89      0.91       674

    accuracy                           0.97      4000
   macro avg       0.95      0.94      0.94      4000
weighted avg       0.97      0.97      0.97      4000

In [96]:
de=DecisionTreeClassifier(random_state=42)

In [97]:
de.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [131]:
y3_pred=de.predict(X_test)

In [132]:
de.score(X_train,y_train)*100

100.0

In [133]:
de.score(X_test,y_test)*100

96.375

In [134]:
print("Accuracy  :", accuracy_score(y_test, y3_pred))
print("Precision :", precision_score(y_test, y3_pred))
print("Recall    :", recall_score(y_test, y3_pred))
print("F1-Score  :", f1_score(y_test, y3_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y3_pred))

print("\nClassification Report:")
print(classification_report(y_test, y3_pred))

Accuracy  : 0.96375
Precision : 0.8930163447251115
Recall    : 0.8916913946587537
F1-Score  : 0.8923533778767632

Confusion Matrix:
[[3254   72]
 [  73  601]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      3326
           1       0.89      0.89      0.89       674

    accuracy                           0.96      4000
   macro avg       0.94      0.94      0.94      4000
weighted avg       0.96      0.96      0.96      4000

In [100]:
knn=KNeighborsClassifier(n_neighbors=5)

In [101]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [136]:
y4_pred=de.predict(X_test)

In [137]:
knn.score(X_train,y_train)*100

93.36875

In [138]:
knn.score(X_test,y_test)*100

89.225

In [139]:
print("Accuracy  :", accuracy_score(y_test, y4_pred))
print("Precision :", precision_score(y_test, y4_pred))
print("Recall    :", recall_score(y_test, y4_pred))
print("F1-Score  :", f1_score(y_test, y4_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y4_pred))

print("\nClassification Report:")
print(classification_report(y_test, y4_pred))

Accuracy  : 0.96375
Precision : 0.8930163447251115
Recall    : 0.8916913946587537
F1-Score  : 0.8923533778767632

Confusion Matrix:
[[3254   72]
 [  73  601]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      3326
           1       0.89      0.89      0.89       674

    accuracy                           0.96      4000
   macro avg       0.94      0.94      0.94      4000
weighted avg       0.96      0.96      0.96      4000

In [104]:
svm=SVC(kernel='linear',random_state=42)

In [105]:
svm.fit(X_train,y_train)

SVC(kernel='linear', random_state=42)

In [140]:
y5_pred=de.predict(X_test)

In [141]:
svm.score(X_train,y_train)*100

98.0375

In [142]:
svm.score(X_test,y_test)*100

97.32499999999999

In [143]:
print("Accuracy  :", accuracy_score(y_test, y5_pred))
print("Precision :", precision_score(y_test, y5_pred))
print("Recall    :", recall_score(y_test, y5_pred))
print("F1-Score  :", f1_score(y_test, y5_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y5_pred))

print("\nClassification Report:")
print(classification_report(y_test, y5_pred))

Accuracy  : 0.96375
Precision : 0.8930163447251115
Recall    : 0.8916913946587537
F1-Score  : 0.8923533778767632

Confusion Matrix:
[[3254   72]
 [  73  601]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      3326
           1       0.89      0.89      0.89       674

    accuracy                           0.96      4000
   macro avg       0.94      0.94      0.94      4000
weighted avg       0.96      0.96      0.96      4000

In [144]:
models = {
    "Logistic Regression" : lr,
    "Decision Tree"       : de,
    "Random Forest"       : re,
    "KNN"                 : knn,
    "SVM"                 : svm,
}

results = []

for name, model in models.items():
    y_pred = model.predict(X_test)
    results.append({
        "Model"     : name,
        "Accuracy"  : round(accuracy_score(y_test, y_pred), 4),
        "Precision" : round(precision_score(y_test, y_pred), 4),
        "Recall"    : round(recall_score(y_test, y_pred), 4),
        "F1-Score"  : round(f1_score(y_test, y_pred), 4),
    })


df_results = pd.DataFrame(results)

df_results = df_results.sort_values("F1-Score", ascending=False).reset_index(drop=True)

print(df_results.to_string(index=False))


best = df_results.iloc[0]["Model"]
print(f"\n✔ Best Model : {best}")

              Model  Accuracy  Precision  Recall  F1-Score
Logistic Regression    0.9735     0.9383  0.9021    0.9198
                SVM    0.9732     0.9355  0.9036    0.9192
      Random Forest    0.9692     0.9285  0.8858    0.9066
      Decision Tree    0.9637     0.8930  0.8917    0.8924
                KNN    0.8922     0.8738  0.4214    0.5686

✔ Best Model : Logistic Regression